name: UpdateBallotComments

on:
  discussion:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Pages site
        uses: actions/checkout@v4
        with:
          repository: HL7Austria/hl7austria.github.io
          ref: pages
          path: site

      - name: Set IG Subfolder name
        id: set_folder
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          echo "Detected branch: $BRANCH_NAME"
          echo "IG_FOLDER=r5-ELGA-e-medikation-$BRANCH_NAME" >> $GITHUB_ENV

      - name: Fetch Discussions and Generate comments.json
        working-directory: site/${{ env.IG_FOLDER }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p temp
          NEXT="null"
          echo '[]' > temp/discussions-all.json

          while [ "$NEXT" != "null" ]; do
            echo "Fetching discussions after cursor: $NEXT"
            if [ "$NEXT" = "null" ]; then
              gh api graphql -F query='{
                repository(owner: "HL7Austria", name: "ELGA-FHIR-e-Medikation-R5") {
                  discussions(first: 100) {
                    pageInfo { endCursor hasNextPage }
                    nodes {
                      title
                      body
                      url
                      number
                      createdAt
                      category { name }
                    }
                  }
                }
              }' > temp/page.json
            else
              gh api graphql -F query='query($cursor: String!) {
                repository(owner: "HL7Austria", name: "ELGA-FHIR-e-Medikation-R5") {
                  discussions(first: 100, after: $cursor) {
                    pageInfo { endCursor hasNextPage }
                    nodes {
                      title
                      body
                      url
                      number
                      createdAt
                      category { name }
                    }
                  }
                }
              }' -f cursor="$NEXT" > temp/page.json
            fi

            jq -s '.[0] + .[1]' temp/discussions-all.json temp/page.json > temp/merged.json
            mv temp/merged.json temp/discussions-all.json

            NEXT=$(jq -r '.data.repository.discussions.pageInfo | if .hasNextPage then .endCursor else "null" end' temp/page.json)
          done

      - name: Generate comments.json
        working-directory: site/${{ env.IG_FOLDER }}
        run: |
          python3 ../scripts/generate-comments.py

      - name: Commit and push updated comments.json
        working-directory: site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f comments/comments.json ]; then
            git add comments/comments.json
            git commit -m "Update comments.json from discussions event" || echo "No changes to commit"
            git push
          else
            echo "No comments.json generated. Skipping commit."
          fi
